---
- name: install nginx server
  hosts: db
  tasks:
    - name: copy nginx rpm
      copy: 
        src: files/nginx-1.17.6-1.el7.centos.x86_64.rpm
        dest: /opt/nginx-1.17.6-1.el7.centos.x86_64.rpm
    - name: install nginx
      yum:
        name: /opt/nginx-1.17.6-1.el7.centos.x86_64.rpm
        state: present
    - name: start service
      service: 
        name: nginx
        state: started
        enabled: yes
